# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from grpc_service import classifier_pb2 as classifier__pb2


class SoundSourceClassifierStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.PredictMusicGenre = channel.unary_unary(
        '/classifier.SoundSourceClassifier/PredictMusicGenre',
        request_serializer=classifier__pb2.MusicGenreRequest.SerializeToString,
        response_deserializer=classifier__pb2.MusicGenreResponse.FromString,
        )
    self.LoadLibrosaSettings = channel.unary_unary(
        '/classifier.SoundSourceClassifier/LoadLibrosaSettings',
        request_serializer=classifier__pb2.LibrosaSettingsRequest.SerializeToString,
        response_deserializer=classifier__pb2.LibrosaSettingsResponse.FromString,
        )


class SoundSourceClassifierServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def PredictMusicGenre(self, request, context):
    """Predict music genre 

    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LoadLibrosaSettings(self, request, context):
    """Load liborsa and mfcc settings
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SoundSourceClassifierServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'PredictMusicGenre': grpc.unary_unary_rpc_method_handler(
          servicer.PredictMusicGenre,
          request_deserializer=classifier__pb2.MusicGenreRequest.FromString,
          response_serializer=classifier__pb2.MusicGenreResponse.SerializeToString,
      ),
      'LoadLibrosaSettings': grpc.unary_unary_rpc_method_handler(
          servicer.LoadLibrosaSettings,
          request_deserializer=classifier__pb2.LibrosaSettingsRequest.FromString,
          response_serializer=classifier__pb2.LibrosaSettingsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'classifier.SoundSourceClassifier', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
