# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: classifier.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='classifier.proto',
  package='classifier',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x63lassifier.proto\x12\nclassifier\"f\n\x11MusicGenreRequest\x12\x0e\n\x06signal\x18\x01 \x03(\x01\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x03\x12\x12\n\nmodel_name\x18\x03 \x01(\t\x12\x18\n\x10librosa_settings\x18\x04 \x01(\t\"_\n\x12MusicGenreResponse\x12\x0e\n\x06genres\x18\x01 \x03(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x11\n\texception\x18\x03 \x01(\t\x12\x16\n\x0e\x65xecution_time\x18\x04 \x01(\x05\x32k\n\x15SoundSourceClassifier\x12R\n\x11PredictMusicGenre\x12\x1d.classifier.MusicGenreRequest\x1a\x1e.classifier.MusicGenreResponseb\x06proto3')
)




_MUSICGENREREQUEST = _descriptor.Descriptor(
  name='MusicGenreRequest',
  full_name='classifier.MusicGenreRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signal', full_name='classifier.MusicGenreRequest.signal', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sample_rate', full_name='classifier.MusicGenreRequest.sample_rate', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_name', full_name='classifier.MusicGenreRequest.model_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='librosa_settings', full_name='classifier.MusicGenreRequest.librosa_settings', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=134,
)


_MUSICGENRERESPONSE = _descriptor.Descriptor(
  name='MusicGenreResponse',
  full_name='classifier.MusicGenreResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='genres', full_name='classifier.MusicGenreResponse.genres', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='classifier.MusicGenreResponse.status', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exception', full_name='classifier.MusicGenreResponse.exception', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='execution_time', full_name='classifier.MusicGenreResponse.execution_time', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=231,
)

DESCRIPTOR.message_types_by_name['MusicGenreRequest'] = _MUSICGENREREQUEST
DESCRIPTOR.message_types_by_name['MusicGenreResponse'] = _MUSICGENRERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MusicGenreRequest = _reflection.GeneratedProtocolMessageType('MusicGenreRequest', (_message.Message,), dict(
  DESCRIPTOR = _MUSICGENREREQUEST,
  __module__ = 'classifier_pb2'
  # @@protoc_insertion_point(class_scope:classifier.MusicGenreRequest)
  ))
_sym_db.RegisterMessage(MusicGenreRequest)

MusicGenreResponse = _reflection.GeneratedProtocolMessageType('MusicGenreResponse', (_message.Message,), dict(
  DESCRIPTOR = _MUSICGENRERESPONSE,
  __module__ = 'classifier_pb2'
  # @@protoc_insertion_point(class_scope:classifier.MusicGenreResponse)
  ))
_sym_db.RegisterMessage(MusicGenreResponse)



_SOUNDSOURCECLASSIFIER = _descriptor.ServiceDescriptor(
  name='SoundSourceClassifier',
  full_name='classifier.SoundSourceClassifier',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=233,
  serialized_end=340,
  methods=[
  _descriptor.MethodDescriptor(
    name='PredictMusicGenre',
    full_name='classifier.SoundSourceClassifier.PredictMusicGenre',
    index=0,
    containing_service=None,
    input_type=_MUSICGENREREQUEST,
    output_type=_MUSICGENRERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SOUNDSOURCECLASSIFIER)

DESCRIPTOR.services_by_name['SoundSourceClassifier'] = _SOUNDSOURCECLASSIFIER

# @@protoc_insertion_point(module_scope)
